-- DISPLAY STRUCTURES
-- ------------------
> SHOW DATABASES 
> SHOW TABLES    
> DESC [TABLE]

-- OPERATORS
-- ---------
> COMPARISON  ( = , != , < , > , <= , >= , BETWEEN )
> LOGICAL BOOLEAN ( AND , OR , IN , NOT )
> ARITHMETIC ( + , - , * , / ) 

-- FUNCTIONS
-- ---------
> UPPER([COLUMN]) , LOWER([COLUMN])
> NOW() = CURDATE() , CURTIME()
> SQRT([COLUMN])
> AVG([COLUMN]) , MAX([COLUMN]) , MIN([COLUMN])
  COUNT([COLUMN]) , SUM([COLUMN])

-- JOIN
-- ----
> INNER JOIN
> LEFT OUTER JOIN , RIGHT OUTER JOIN

-- CREATE STATEMENT
-- ----------------
> CREATE DATABASE [DATABASE] | USE [DATABASE]
> CREATE TABLE [TABLE] (
	[COLUMN] VARCHAR(3) AUTO_INCREMENT,
	[COLUMN] DATE,
	...,
	PRIMARY KEY ([COLUMN]),
	FOREIGN KEY ([COLUMN]) REFERENCES [TABLE]([COLUMN])
  )
> CREATE OR REPLACE VIEW [VIEW] AS SELECT ...
> INSERT INTO [TABLE] VALUES (VAL1, VAL2, ...)
> INSERT INTO [TABLE] VALUES
  (VAL1, VAL2, ...),
  (VAL1, VAL2, ...),
  ...
> INSERT INTO [TABLE] ([COL1, COL2])
  VALUES (VAL1, VAL2)

-- READ STATEMENT
-- --------------
> SELECT * FROM [TABLE]
> SELECT [COLUMN] FROM [TABLE]
  SELECT [TABLE].[COLUMN] FROM [TABLE]
> SELECT [COL1, COL2, ...] FROM [TABLE]
> SELECT DISTINCT [COLUMN] FROM [TABLE]
> SELECT * FROM [TABLE] ORDER BY [COLUMN] ASC/DESC
> SELECT [FUNCTIONS] FROM [TABLE] GROUP BY [COLUMN]
> SELECT * FROM [TABLE] LIMIT [RANGE]
  SELECT * FROM [TABLE] LIMIT [START_AFTER],[RANGE]
> SELECT * FROM [TABLE] WHERE [COLUMN]=[VALUE]
  	... WHERE [COLUMN] [COMPARISON] [VALUE]
  		[LOGICAL] [COMPARISON] [VALUE]
  	... WHERE [COLUMN] [COMPARISON] [VALUE]
  		[LOGICAL] (
			[COLUMN] [COMPARISON] [VALUE]
  			[LOGICAL] [COMPARISON] [VALUE]
  		)
  	... WHERE [COLUMN] IN (VAL1, VAL2, ...)
> SELECT * FROM [TABLE] WHERE [COLUMN] LIKE '%[VALUE]%'  
  ... LIKE '%[[VAL1],[VAL2],[..]]%' = OPTIONS
  ... LIKE '[A-Z]' 					= RANGE OF LETTERS
  ... LIKE '[VAL1]_%_%_%'			= 4 FIX CHARACTER SIZE
> SELECT CONCAT([COL1]'is'[COL2]) AS [NEW_COLUMN]
  FROM [TABLE]
> SELECT * FROM [TABLE]
  WHERE [COLUMN] > (
  	SELECT ... )
  ORDER BY ...
> SELECT [COL1], [COL2], [...]
  FROM [TABLE1] JOIN [TABLE2]
  ON [COL_PK] = [COL_FK]
> SELECT .. UNION .. SELECT

-- UPDATE STATEMENT
-- ----------------
> ALTER TABLE [TABLE]
  ADD COLUMN [COLUMN] VARCHAR(3)
  AFTER [COLUMN]
> UPDATE [TABLE] SET [COLUMN]=[VALUE]
  WHERE [COLUMN]=[VALUE]
> ALTER TABLE [TABLE] MODIFY
  [COLUMN] VARCHAR(15)
> ALTER TABLE [TABLE]
  AUTO_INCREMENT = [VALUE]
> ALTER TABLE [TABLE] ADD CONSTRAINT [CONSTRAINT_NAME] 
  FOREIGN KEY ([COLUMN]) REFERENCES [TABLE]([COLUMN])
> ALTER TABLE [TABLE] CHANGE
  [COLUMN] [RENAMED_COLUMN] VARCHAR(50)
> RENAME TABLE [TABLE] TO [RENAMED_TABLE]

-- DELETE STATEMENT
-- ----------------
> DROP DATABASE [DATABASE]
> DROP TABLE [TABLE]
> DROP VIEW [VIEW]
> TRUNCATE TABLE [TABLE]
> DELETE FROM [TABLE] WHERE [COLUMN]=[VALUE]
> ALTER TABLE [TABLE]
  DROP COLUMN [COLUMN];


ALTER TABLE TB_PET ADD CONSTRAINT 
fk_id_owner FOREIGN KEY (ID_OWNER) 
REFERENCES TB_OWNER(ID);
  
-- SEARCH STATEMENT
-- ----------------