USE ICANG;

SELECT COUNT(MW.NAMA) AS 'MAHASISWA LULUS 2020-2021'
FROM TB_JADWAL_KULIAH JK 
INNER JOIN TB_NILAI_MATKUL NM ON JK.KODE_KELAS = NM.KODE_KELAS
INNER JOIN TB_MAHASISWA MW ON NM.NIM = MW.NIM
WHERE JK.TA = '2020-2021' AND NM.NILAI IN (
	SELECT NILAI FROM TB_JADWAL_KULIAH
	WHERE NILAI LIKE 'A%' OR 
	NILAI LIKE 'B%' OR
	NILAI LIKE 'C'
)

